export const INITIALIZE_SAGA = 'INITIALIZE_SAGA';
export const UNSUBSCRIBE_SAGA = 'UNSUBSCRIBE_SAGA';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_USER_BALANCE = 'SET_USER_BALANCE';
export const LOADING_USER_BALANCE = 'LOADING_USER_BALANCE';

export const BUY_FORM = 'BUY_FORM';
export const SELL_FORM = 'SELL_FORM';

export const TOKEN_EXCHANGE_CONTRACT = 'TOKEN_EXCHANGE_CONTRACT';
export const FUN_TOKEN_CONTRACT = 'FUN_TOKEN_CONTRACT';
