export const INITIALIZE_SAGA = 'INITIALIZE_SAGA';
export const UNSUBSCRIBE_SAGA = 'UNSUBSCRIBE_SAGA';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_USER_BALANCE = 'SET_USER_BALANCE';
export const LOADING_USER_BALANCE = 'LOADING_USER_BALANCE';
